# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  drive1_joint:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: false
    max_acceleration: 0
  drive2_joint:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: false
    max_acceleration: 0
  drive3_joint:
    has_velocity_limits: true
    max_velocity: 2.00
    has_acceleration_limits: false
    max_acceleration: 0
  drive4_joint:
    has_velocity_limits: true
    max_velocity: 2.00
    has_acceleration_limits: false
    max_acceleration: 0
  drive5_joint:
    has_velocity_limits: true
    max_velocity: 2.00
    has_acceleration_limits: false
    max_acceleration: 0
  drive6_joint:
    has_velocity_limits: true
    max_velocity: 2.00
    has_acceleration_limits: false
    max_acceleration: 0
  robco_left_finger_joint:
    has_velocity_limits: true
    max_velocity: 3.1400000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  robco_left_fingertip_joint:
    has_velocity_limits: true
    max_velocity: 3.1400000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  robco_right_finger_joint:
    has_velocity_limits: true
    max_velocity: 3.1400000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  robco_right_fingertip_joint:
    has_velocity_limits: true
    max_velocity: 3.1400000000000001
    has_acceleration_limits: false
    max_acceleration: 0
